MainProject/Entities/BaseEntity/BaseEntity.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MainProject.Entities.BaseEntity
{
	public abstract class BaseEntity<T> : IBaseEntity<T>
	{
		[Key]
		public virtual T Id { get; set; }
		public virtual DateTime? DateOfBirth { get; set; }
	}
}

MainProject/Entities/BaseEntity/IBaseEntity.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MainProject.Entities.BaseEntity
{
	public interface IBaseEntity<T>
	{
		T Id { get; set; }
		DateTime? DateOfBirth { get; set; }
	}
}

MainProject/Entities/ImportedFileRowData.cs
using MainProject.Entities.BaseEntity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MainProject.Entities
{
	[Table("tblFileData")]
	public class ImportedFileRowData: BaseEntity<int>
	{		
		public string Name { get; set; }		
		public bool IsMarried { get; set; }
		public string Phone { get; set; }

		[Column(TypeName = "decimal(18,4)")]
		public decimal Salary { get; set; }
	}
}

MainProject/Models/ErrorViewModel.cs
using System;

namespace MainProject.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

MainProject/Models/UserVM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MainProject.Models
{
	public class UserVM
	{
		[Display(Name = "Id")]
		public int Id { get; set; }

		[Display(Name = "User name")]
		public string Name { get; set; }

		[Display(Name = "Date of birth")]

		public DateTime? DateofBirth { get; set; }

		[Display(Name = "Is married")]
		public bool IsMarried { get; set; }

		[Display(Name = "Phone")]
		public string Phone { get; set; }

		[Display(Name = "Salary")]
		public decimal Salary { get; set; }
	}
}

MainProject/Controllers/FileController.cs
using MainProject.Models;
using MainProject.Services.Interfaces;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;

namespace MainProject.Controllers
{
	public class FileController : Controller
	{
		private readonly IWebHostEnvironment _env;
		private readonly IFileUploadDataService _fileService;
		public FileController(IWebHostEnvironment env, IFileUploadDataService fileService)
		{
			_env = env;
			_fileService = fileService;
		}

		[HttpGet]
		public async Task<IActionResult> Index()
		{
			var userModel = _fileService.GetAllUsers();
			return await Task.Run(() => View(userModel));
		}

		[HttpPost]
		public async Task<IActionResult> FileDownloader(IFormFile file)
		{
			var userModel = _fileService.GetAllUsers();
			ViewBag.Message = null;
			ViewBag.ConvertationIsSucces = null;

			if (file == null)
			{
				ViewBag.Message = "invalid file format";
				return await Task.Run(() => View("Index", userModel));
			}				
			
			bool convertationIsSucces = false;
			if (Path.GetExtension(file.FileName) == ".csv" || Path.GetExtension(file.FileName) == ".xlsx")
			{
				convertationIsSucces = _fileService.HandleUploadedFile(file);
				userModel = _fileService.GetAllUsers();
				ViewBag.ConvertationIsSucces = convertationIsSucces;
				return await Task.Run(() => View("Index", userModel));
			}

			ViewBag.Message = "invalid file format";
			return await Task.Run(() => View("Index", userModel));			
		}

		[HttpGet]		
		public async Task<IActionResult> DeleteRequest(int id)
		{
			if (id == 0)
			{
				Response.StatusCode = 403;
				return PartialView("Error");				
			}
			return await Task.Run(() => View(_fileService.GetSingleUser(id)));
		}

		[HttpPost]
		public async Task<JsonResult> DeleteConfirmation(int id)
		{
			_fileService.RemoveUser(id);
			return await Task.Run(() => Json(new { status = "Success" }));
		}
	}
}

MainProject/Controllers/HomeController.cs
using MainProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MainProject.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

MainProject/Views/File/DeleteRequest.cshtml
@model MainProject.Models.UserVM
@{
	//ViewData["Title"] = "Delete";
	Layout = null;
}

<div class="modal-body">
	@Html.LabelFor(model => model.Id):
	<b>@Html.DisplayFor(model => model.Id)</b>
	<br />

	@Html.LabelFor(model => model.Name):
	<b>@Html.DisplayFor(model => model.Name)</b>
	<br />

	@Html.LabelFor(model => model.DateofBirth):
	<b>@Html.DisplayFor(model => model.DateofBirth)</b>
	<br />

	@Html.LabelFor(model => model.IsMarried):
	<b>@Html.DisplayFor(model => model.IsMarried)</b>
	<br />

	@Html.LabelFor(model => model.Phone):
	<b>@Html.DisplayFor(model => model.Phone)</b>
	<br />

	@Html.LabelFor(model => model.Salary):
	<b>@Html.DisplayFor(model => model.Salary)</b>
	<br />
</div>

MainProject/Views/File/Index.cshtml
@model IEnumerable<UserVM>
@{
	var data = ViewBag.ConvertationIsSucces;
	var message = ViewBag.Message;
}

@*convertation result notification check*@
@if (data != null)
{
	<input type="hidden" id="convertatioNotification" value="@data.ToString()" />
}

@*file format acceptability notification check*@
@if (message != null)
{

	<input type="hidden" id="wrongFileFormatNotification" value="@message.ToString()" />
}

<div class="text-center">
	<h4 class="display-4">Upload your .csv / .xlsx file</h4>
</div>
<hr />
<br />

@*file upload field*@
<h4 id="warning" class="text-center text-danger" style="margin-bottom: 20px;"></h4>
<div class="container">
	<div class="row">
		<div class="col-md-3">
		</div>
		<div class="col-md-6">
			<form asp-controller="File" asp-action="FileDownloader" enctype="multipart/form-data" method="post">
				<div class="input-group mb-3">
					<div class="input-group-prepend">
						<button class="btn btn-secondary" type="submit">Upload</button>
					</div>
					<div class="custom-file">
						<input type="file" name="file" class="custom-file-input" id="dataFile">
						<label class="custom-file-label" for="dataFile">Choose file</label>
					</div>
				</div>
			</form>
		</div>
		<div class="col-md-3">
		</div>
	</div>
</div>

@*table search records*@

<div class="row">
	<div class="col-md-9"></div>
	<div class="col-md-3">
		<div class="input-group input-group-sm mb-3">
			<div class="input-group-prepend">
				<span class="input-group-text" id="inputGroup-sizing-sm">Search</span>
			</div>
			<input type="search" id="search"
				   class="form-control search-input"
				   aria-label="Small" aria-describedby="inputGroup-sizing-sm"
				   data-table="customers-list">
		</div>
	</div>
</div>



@*table of converted records*@
<div class="row justify-content-center">
	<div class="col-md-12">
		@if (Model != null)
		{
			<table id="records" class="table table-striped table-sm table-hover customers-list">
				<thead class="thead-dark">
					<tr>
						<th>Id</th>
						<th>Name</th>
						<th>Birth date</th>
						<th>Is married</th>
						<th>Phone</th>
						<th>Salary</th>
						<th scope="col"></th>
					</tr>
				</thead>
				<tbody>
					@foreach (var item in Model)
					{
						<tr id="row_@item.Id">
							<th scope="row">@item.Id</th>
							<td>@item.Name</td>
							<td>@item.DateofBirth.Value.ToString("yyyy-MM-dd")</td>
							<td>@item.IsMarried.ToString()</td>
							<td>@item.Phone</td>
							<td>@item.Salary.ToString()</td>
							<td>
								<a href="#" id="@item.Id"
								   onclick="RecordDeleteRequest(this.id)"
								   class=" ml-1">
									<i class="fa fa-trash-alt fa-lg"></i>
								</a>
							</td>
						</tr>
					}
				</tbody>
			</table>
		}
	</div>

	@*modal for delete*@
	<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
		<div class="modal-dialog" id="dialogContent" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title text-center" id="exampleModalLabel">Do you want to delete this record?</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body">
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
					<button type="button" class="btn btn-primary" onclick="ConfirmDelete()">Confirm </button>
				</div>
			</div>
		</div>
	</div>
</div>
<input type="hidden" id="hiddenRecordId" />



@section scripts
{
	<script type="text/javascript">

		// check file format
		$('#dataFile').on('change', function () {
			//get the file name
			var fileName = $(this).val();

			var extension = fileName.substring(fileName.lastIndexOf('.') + 1);
			if (extension != "csv" || extension != "xlsx")
				$('#warning').text("acceptable file extensions: .csv / .xlsx");
			if (extension == "csv" || extension == "xlsx")
				$('#warning').text("");
			//replace the "Choose a file" label
			$(this).next('.custom-file-label').html(fileName);
		});

		// notifier work
		$(document).ready(function () {
			var val_1 = $('#wrongFileFormatNotification').val();
			if (val_1 == "invalid file format") {
				toastr.warning("Invalid file format");
			}

			var val_2 = $('#convertatioNotification').val();
			console.log("result:", val_2)
			if (val_2 == "True") {
				toastr.success("File converted succesfully");
			}
			if (val_2 == "False") {
				toastr.error("File convertation error");
			}
		});

		//request to remove record
		function RecordDeleteRequest(id) {
			$("#hiddenRecordId").val(id);
			$.get("@Url.Action("DeleteRequest", "File")/" + id,
				function (data) {
					$('.modal-body').html(data);
				})
			$('#myModal').modal('show');
		}

		//record removing
		var ConfirmDelete = function () {
			var recId = $("#hiddenRecordId").val();
			$.ajax({
				type: "POST",
				url: "/File/DeleteConfirmation",
				data: { Id: recId },
				success: function (result) {
					$("#row_" + recId).remove();
					$("#myModal").modal('hide');
				}
			})
		};


		// SEARCHING + SORTING code in wwww/js/site.js

	</script>
}

MainProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MainProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - MainProject</title>
	<link rel="stylesheet" href="~/css/site.css" />
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.23/css/jquery.dataTables.css">
	<link href="~/lib/toastr.js/toastr.min.css" rel="stylesheet" />

</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container">
				<a class="navbar-brand" asp-area="" asp-controller="File" asp-action="Index">File downloader</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
					<ul class="navbar-nav flex-grow-1">
						@*<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
							</li>*@
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<br />
	<br />
	<br />
	<br />
	<footer class="border-top footer text-muted" style="margin-top: 100px;">
		<div class="container">
			&copy; 2021 - MainProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

	@*library for anabling notifications*@
	<script src="~/lib/toastr.js/toastr.min.js"></script>

	@*table sorting library*@
	<script src="~/tablesort/tablesort.min.js"></script>
	<script src="~/tablesort/sorts/tablesort.date.min.js"></script>
	<script src="~/tablesort/sorts/tablesort.dotsep.min.js"></script>
	<script src="~/tablesort/sorts/tablesort.filesize.min.js"></script>
	<script src="~/tablesort/sorts/tablesort.monthname.min.js"></script>
	<script src="~/tablesort/sorts/tablesort.number.min.js"></script>

	@*another table sorting library*@
	<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.js"></script>

	<script src="https://kit.fontawesome.com/5327974dc8.js" crossorigin="anonymous"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@RenderSection("Scripts", required: false)
</body>
</html>